name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y python3-pip curl
      - name: Build docs (required for tests)
        run: make

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests, formatting, vetting and linting
        run: make check
      - name: Run coverage
        run: make coverage